### ISSUE TITLE
Referral earning

### ISSUE THREAD

**Issue by chayan69** [zulurepublic/liteIM#4]
Hello,I am a user of lite.im and I  have invited my friends on whatsapp to join lite.im and they signed up using my referral code but I didn't get any btc for inviting my friend.Please tell me why didn't I earn money for inviting them?

**Comment by majestic84** [comment]
Hi, when you go to “Claim Rewards” does it say that you have pending earnings? The reason I ask is because we do not do payouts immediately, we allow the rewards to accumulate so that we can batch them together into a single transaction. We distribute these periodically about every 2-3 days. We are planning on distributing rewards today, however first we must resolve an issue we are having right now where the WhatsApp bot is not responding at all due to an error with the WhatsApp Business API. We are working with our partner at WhatsApp to resolve this as soon as possible.
